### ISSUE TITLE
Question: Plans to support NRT?

### ISSUE THREAD

**Issue by udaken** [xoofx/SharpYaml#109]
Several changes are required to support Nullable reference types.

- `LangVersion` must be 8 or higher.
- Some annotations need to be incorporated.
- The code needs to be more modernized.
- We should add net6.0 to TFM if necessary.

Are these changes acceptable?

**Comment by xoofx** [comment]
Yes, that will be quite some work (you seem motivated though! 😅 )
but as long as we keep the support for netstandard 2.0 for now, it should be fine.

**Comment by udaken** [comment]
I think very many changes are needed.
Maybe we should start with annotations.

I will keep netstandard2.0 support because it is important.
