### ISSUE TITLE
Reusing Serializer instance errors

### ISSUE THREAD

**Issue by bdovaz** [xoofx/SharpYaml#115]
If I try to reuse the Serializer instance, I have problems. The second time I try to serialize an instance in which it has properties of type string I get artifacts of type:

*o0
*o1
*o2
...

And at the time of serializing evidently I get errors of the type:

```
SharpYaml.Serialization.AnchorNotFoundException : (Lin: 0, Col: 0, Chr: 0) - (Lin: 0, Col: 3, Chr: 3): Unable to find alias.
```

It can be easily reproduced in a test:

```csharp
[Test]
public void Test()
{
    var serializer = new Serializer();

    object data = new
    {
        PropertyOne = "testData"
    };

    for (int i = 0; i < 10; i++)
    {
        var text = serializer.Serialize(data);
        var newValue = serializer.Deserialize(text);
    }
}
```

I can do a PR but you would have to guide me a little bit where to look @xoofx.

Thanks!

**Comment by bdovaz** [comment]
I see that it has to do with the EmitAlias value that by default is true, if I set it to false, it does not pass.

I don't understand the use of EmitAlias, what is it for?

**Comment by xoofx** [comment]
> I see that it has to do with the EmitAlias value that by default is true, if I set it to false, it does not pass.

Yes, afair, EmitAlias is the only thing that makes the Serializer not reusable by default as it is storing references. Emit Alias is the feature of YAML where if you emit an object multiple times, it will use anchor/reference instead of duplicating the object in the output YAML.

The default has been like this since ages. It's probably not great, but well, you can turn it off, so let's keep it that way.

**Comment by bdovaz** [comment]
But is there a way to make a change (and create a PR) to be able to reuse the instance with EmitAlias to true?

If you guide me a bit where to look I can try, otherwise it would be to make a PR of the Readme.md indicating it so at least that whoever uses it knows it.

**Comment by xoofx** [comment]
> But is there a way to make a change (and create a PR) to be able to reuse the instance with EmitAlias to true?

Oh sorry, yes, the dictionary are in the AnchorSerializer:

https://github.com/xoofx/SharpYaml/blob/a8fcaa5f69912188319ec6b8f6a2571e90b0071e/src/SharpYaml/Serialization/Serializers/AnchorSerializer.cs#L57-L58

so in the `SerializerSettings` you could add a bool in that says e.g "ResetAlias", and in the `Serializer` class, clear the AnchorSerializer if necessary after a `Serialize`/`Deserialize` call. (The AnchorSerializer is embedded in a RoutingSerializer, you will figure this out).
