### ISSUE TITLE
How to get token locations?

### ISSUE THREAD

**Issue by vasily-kirichenko** [xoofx/SharpYaml#16]
```nemerle
def settings = SerializerSettings() <- 
    { EmitDefaultValues = true; 
      EmitTags = false; 
       SortKeyForMapping = false };
def serializer = Serializer(settings);
def node = serializer.Deserialize(StringReader(text));
```
`node` contains `Dictionary<object, object>` where locations are not present. Is there a way to get them? I mean something like `{ Start = (1, 0), End = (1, 5) }` for `Bar: 2` in
```yaml
Foo: 1
Bar: 2
```

**Comment by xoofx** [comment]
Not straight forward, but it should be possible to get some info by hooking into the serialization pipeline:

If you override the method `ReadDictionaryItem` in [DefaultObjectSerializerBackend](https://github.com/xoofx/SharpYaml/blob/master/SharpYaml/Serialization/Serializers/DefaultObjectSerializerBackend.cs#L107), you should be able to access the `context.Reader.Peek<ParsingEvent>()` to get enough information (before each `ReadYaml` operations)

The override of `DefaultObjectSerializerBackend` should be setup on the `SerializerSettings.ObjectSerializerBackend`

**Comment by vasily-kirichenko** [comment]
Thanks for the answer. OK, I can get location information:
```nemerle
class ObjectSerializerBackend: Serializers.DefaultObjectSerializerBackend
{
    public override ReadDictionaryItem(ctx: ref ObjectContext, keyValueType: KeyValuePair[Type, Type]): KeyValuePair[object, object] {
        def e = ctx.Reader.Peek();
        Message.Hint($"*** ($(e.Start)) => ($(e.End))");
        base.ReadDictionaryItem(ref ctx, keyValueType)
    }
}
```
For this yaml:
```yaml
IntValue: 1
FloatValue: 2.2
StringValue: a string
UriValue: http://domain.com
TimeSpanValue: 1.00:00:05
AnotherIntValue: 22
Person:
  Age: 22
AList:
  - 1
  - 2
```
I get the following output:
```
*** (Lin: 1, Col: 0, Chr: 2) => (Lin: 1, Col: 8, Chr: 10)
*** (Lin: 2, Col: 0, Chr: 15) => (Lin: 2, Col: 10, Chr: 25)
*** (Lin: 3, Col: 0, Chr: 32) => (Lin: 3, Col: 11, Chr: 43)
*** (Lin: 4, Col: 0, Chr: 55) => (Lin: 4, Col: 15, Chr: 70)
*** (Lin: 5, Col: 0, Chr: 76) => (Lin: 5, Col: 6, Chr: 82)
*** (Lin: 6, Col: 2, Chr: 87) => (Lin: 6, Col: 5, Chr: 90)
*** (Lin: 7, Col: 0, Chr: 96) => (Lin: 7, Col: 5, Chr: 101)
```
Looks great, but I cannot see how I can connect this info to parser results.

```nemerle
def settings = SerializerSettings() <- 
{ EmitDefaultValues = true; 
  EmitTags = false; 
  SortKeyForMapping = false;
  ObjectSerializerBackend = ObjectSerializerBackend()
};
def serializer = Serializer(settings);
def node = serializer.Deserialize(StringReader(text));

def loop(n: object) {
	Message.Hint($"Node: $n, type = $(n.GetType())");
	match (n) {
	| l is List[object] => Node.List (l.Map(loop))
	| d is Dictionary[object, object] => 
		Node.Map (d.NToList().Choose(p => {
			match (p.Key) {
			| key is string => Some(key, loop(p.Value))
			| _ => None()
			}}))
	| scalar =>
		Node.Scal (Scalar.FromObj(scalar))
	}
}
```
Output:
```
Node: System.Collections.Generic.Dictionary`2[System.Object,System.Object], type = System.Collections.Generic.Dictionary`2[System.Object,System.Object]
Node: 1, type = System.Int32
Node: 2.2, type = System.Double
Node: a string, type = System.String
Node: 22, type = System.Int32
Node: System.Collections.Generic.Dictionary`2[System.Object,System.Object], type = System.Collections.Generic.Dictionary`2[System.Object,System.Object]
Node: 22, type = System.Int32
Node: System.Collections.Generic.List`1[System.Object], type = System.Collections.Generic.List`1[System.Object]
Node: 2, type = System.Int32
Node: 1, type = System.Int32
```
So, I still have bare `Dictionary`s, `List`s and primitive values and a list of `Mark`s. What do you suggest to do next to match them?

**Comment by xoofx** [comment]
If you want key and value, you need to override and copy the code from `DefaultObjectSerializerBackend.ReadDictionaryItem`, and get ParsingEvent before reading the key (`ReadYaml`), and before reading the value.
Then if you need to connect them back, simply store in static `ConditionalWeakTable` the key as the dictionary being deserialized, and the value, a dictionary of keys and the `Tuple<ParsingEvent for the key, ParsingEvent for the value>`.
