### ISSUE TITLE
PCL Profile 259?

### ISSUE THREAD

**Issue by CumpsD** [xoofx/SharpYaml#17]
Would it be easy for you guys to distribute 2 PCLs in your NuGet package, besides the current Profile 136, to also target Profile 259 ;)

Related to https://github.com/Microsoft/visualfsharp/issues/99 where PCLs from 4.5 and 4.0 dont play nice together

**Comment by xoofx** [comment]
Yes, almost... but the shared project stuff is so badly working with VS (or Resharper) so that it is unusable and we need to workaround to duplicate project files (which is something I don't like...). Unless you have a better idea?

**Comment by adamchester** [comment]
@xoofx by "duplicate project files" do you mean like [FSharp.Data does](https://github.com/fsharp/FSharp.Data/tree/master/src)?

**Comment by xoofx** [comment]
@adamchester yes typically

**Comment by xoofx** [comment]
It can be done differently with solution and properties per solution, without having multiple csproj (what you have is a small file along a PCL45.sln that contains the setup for this target that will be picked up by the csproj), just that it is a bit annoying to setup.

**Comment by CumpsD** [comment]
I honestly have no experience with creation of PCL libraries, I had assumed you could create two projects and link the files in the other one, thus maintaining only one set of files.

**Comment by xoofx** [comment]
Yesterday I have upgraded SharpYaml to use .NET standard. I was not able to target Profile 259, as it doesn't contain `TypeCode` which is used in many places in the code. The switch to the new dotnet core is providing assemblies compatible for .NET 3.5, .NET 4.5, .NET 4+ PCL Profile328 and .NET Standard 1.6. Hope that it should cover most of usages.
