### ISSUE TITLE
property IsUnicode in Emmiter class always returns false

### ISSUE THREAD

**Issue by majocha** [xoofx/SharpYaml#19]
Comparing various utf encodings coming from outside world to these few defaults provided by .Net framework is very likely to fail. In fact both StringWriter and a StreamWriter returned from File.CreateText are not recognized as Unicode.

I'm not sure what is the correct way to do this but

```
private bool IsUnicode => output.Encoding.WebName.Contains("utf");
```

seems to work fine.

**Comment by xoofx** [comment]
Fixed by a83d1836dc5d40ad7a5f53c90a92fd92e6794fd2
