### ISSUE TITLE
Parse block with value gives SemanticErrorException

### ISSUE THREAD

**Issue by toroso** [xoofx/SharpYaml#21]
The following yaml I believe is valid (looking at e.g. `bill-to` at [yaml.org](http://www.yaml.org/start.html)). However, parsing it gives me a SemanticErrorException.

    root: someValue
        blockKey: someOtherValue

Strangely, adding a comment (also valid) also gives SemanticErrorException but with another stack trace and error message.

    root: someValue
        # A comment
        blockKey: someOtherValue

Here's a test:

            [Test]
            public void ParseValueAndBlock()
            {
                const string yaml =
    @"root: someValue
        blockKey: someOtherValue
    ";

                var reader = new StringReader(yaml);
                var stream = new YamlStream();
                stream.Load(reader); // throws SemanticErrorException
            }

Tested with version 1.5.3.

**Comment by xoofx** [comment]
There error is normal. You can't have a first a) `key: value`, with a nested b) `key:value`. The b) would work only if a) didn't have a value (only the key)

The example `bill-to` is different as it is not a value but an anchor for the nested object.

**Comment by toroso** [comment]
Ok, my bad. Thanks!
