### ISSUE TITLE
Can't Run at Windows XP

### ISSUE THREAD

**Issue by agrozyme** [xoofx/SharpYaml#22]
I make a simple WPF application with .NET4 at Windows 10, and copy all .exe / .dll to a Windows XP at a VirtualBox VM.
It can run good at Windows 10, but not run at Windows XP.

**Comment by xoofx** [comment]
Most likely a .NET version not supported there. The latest 1.6 provides 3.5 and 4.5 compatible .NET version, so it should be working with them.
