### ISSUE TITLE
How to specify string enum de/serialization? 

### ISSUE THREAD

**Issue by n9** [xoofx/SharpYaml#25]
I want to serialize/deserialize enums using their string names. What is the appropriate way to specify this in SharpYaml? (For instance in JSON.NET, I would use [StringEnumConverter](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs).)

**Comment by xoofx** [comment]
You don't have to specify anything, as it should already work... have you tried? (See for example this [test](https://github.com/xoofx/SharpYaml/blob/a83d1836dc5d40ad7a5f53c90a92fd92e6794fd2/SharpYaml.Tests/Serialization/SerializationTests2.cs#L228))

**Comment by n9** [comment]
You are right. I was getting an NPE. And I thought that string enums are not supported. However, the reason for exception was different. Thank you for fast response.
