### ISSUE TITLE
SharpYaml dependencies

### ISSUE THREAD

**Issue by sergey-tihon** [xoofx/SharpYaml#54]
Latest version `v1.6.3` has dependency on `System.Reflection.TypeExtentions` `v.4.1.0.0`
<img width="440" alt="win10_-_fall_creators" src="https://user-images.githubusercontent.com/1197905/39351039-c8710d5e-4a08-11e8-9dbd-14aa481c3504.png">

`nuspec` say that you depend on `system.reflection.typeextensions.4.3.0.nupkg` or later. 
There is a dll inside this NuGet package in `lib\netstandard1.5\` that has version `4.1.1.0`
<img width="416" alt="win10_-_fall_creators" src="https://user-images.githubusercontent.com/1197905/39351169-5aa0550e-4a09-11e8-8af7-f8dc0e8ac460.png">

So, there is no way to use `SharpYaml` wihtout binding redirects =(
It is possible to fix it?

**Comment by sergey-tihon** [comment]
Sorry, I did provide bad interpretation of the issue...
Yes, I do compile `FSharp.Configuration` for `netstandard2.0` and then it fails at runtime because cannot load `System.Reflection.TypeExtentions` `4.1.0.0` referenced by `SharpYaml`
<img width="451" alt="win10_-_fall_creators" src="https://user-images.githubusercontent.com/1197905/39358052-6f60a908-4a1d-11e8-85ae-dd13694b59fa.png">

**Comment by xoofx** [comment]
For netstandard2.0, many issues are somehow resolved by providing a dedicated netstandard2.0 version, so PR welcome if you want.

**Comment by sergey-tihon** [comment]
@xoofx Thank you recommendations and support here.
This not a issue for me anymore, so I close the issue.
