### ISSUE TITLE
Serialization of private properties

### ISSUE THREAD

**Issue by alexrp** [xoofx/SharpYaml#77]
It seems that if a property has e.g. a `private set` accessor, SharpYaml will skip the property entirely during deserialization.

Would it be possible to support this scenario? I'm loading a bunch of data from disk that is meant to be immutable at run-time, so I would prefer if I could keep property setters private.

**Comment by xoofx** [comment]
There is a PR #61 that might cover your scenario. Otherwise you will have to make a PR for that.

**Comment by alexrp** [comment]
That PR indeed covers my use case, so I'll close this.
