### ISSUE TITLE
Ignore unmapped properties in YAML

### ISSUE THREAD

**Issue by Cinchoo** [xoofx/SharpYaml#90]
Given a YAML file that contains more information than the object deserializing it, the current implementation will throw an exception because there is not a corresponding object property for all properties in the YAML file.

**Comment by krisrok** [comment]
```
new SharpYaml.Serialization.SerializerSettings()
{
    IgnoreUnmatchedProperties = true
}
```
doesn't this help?

**Comment by nickcampau** [comment]
> ```
> new SharpYaml.Serialization.SerializerSettings()
> {
>     IgnoreUnmatchedProperties = true
> }
> ```
> 
> doesn't this help?

I am seeing the same issue. Setting the property `IgnoreUnmatchedProperties ` to `true` only works if the the property's value is a primitive type. For any property that is set to a map or list will throw an exception.

**Comment by Benna96** [comment]
Seeing the same. Getting `Expected 'Scalar', got 'MappingStart'` error when setting `IgnoreUnmatchedProperties` to `true` and the yaml having an unmatched property that's a map.

**Comment by bdovaz** [comment]
Same problem...

@xoofx can you guide me a little? I can try to create a PR.

I understand that the problem has to be around here:

https://github.com/xoofx/SharpYaml/blob/f7960e28f9461d4e60bcd04f622f413548937dc1/src/SharpYaml/Serialization/Serializers/ObjectSerializer.cs#L197

https://github.com/xoofx/SharpYaml/blob/f7960e28f9461d4e60bcd04f622f413548937dc1/src/SharpYaml/Serialization/Serializers/ObjectSerializer.cs#L234
