### ISSUE TITLE
License Confusion

### ISSUE THREAD

**Issue by udaken** [xoofx/SharpYaml#99]
SharpYaml is represented in [LICENSE.txt](https://github.com/xoofx/SharpYaml/blob/master/LICENSE.txt) as a MIT license.

However, [NuGet](https://www.nuget.org/packages/SharpYaml/) shows it as a BSD-2-Clause license.

This seems to be an incorrect [`PackageLicenseExpression`](https://github.com/xoofx/SharpYaml/blob/3105d16b39f83997857d997fc8d3649ca3c9a0d6/src/SharpYaml/SharpYaml.csproj#L15).

**Comment by xoofx** [comment]
Indeed, it's a copy-pasta-typo in NuGet, should be MIT.
